export const ORDER_ICECREAM = "ORDER_ICECREAM";
export const ADD_ICECREAM = "ADD_ICECREAM";
export const ORDER_ICECREAM_SUCCESS = "ORDER_ICECREAM_SUCCESS";
export const ADD_ICECREAM_SUCCESS = "ADD_ICECREAM_SUCCESS";