export const FETCH_TODOS_REQ = 'FETCH_TODOS_REQ'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'

export const ADD_TODO_REQ = 'ADD_TODO_REQ'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

export const EDIT_TODO_REQ = 'EDIT_TODO_REQ'
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS'
export const EDIT_TODO_FAILURE = 'EDIT_TODO_FAILURE'

export const DELETE_TODO_REQ = 'DELETE_TODO_REQ'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'