export const ADD_TO_CART_REQ = 'ADD_TO_CART_REQ'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE'

export const ADD_MORE_TO_CART_REQ = 'ADD_MORE_TO_CART_REQ'
export const ADD_MORE_TO_CART_SUCCESS = 'ADD_MORE_TO_CART_SUCCESS'
export const ADD_MORE_TO_CART_FAILURE = 'ADD_MORE_TO_CART_FAILURE'

export const REMOVE_FROM_CART_REQ = 'REMOVE_FROM_CART_REQ'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE'

export const FETCH_CART_REQ = 'FETCH_CART_REQ'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_ERROR = 'FETCH_CART_ERROR'