export const FETCH_PRODUCTS_REQ = 'FETCH_PRODUCTS_REQ'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

export const DECREASE_QUANTITY_REQUEST = 'DECREASE_QUANTITY_REQUEST'
export const DECREASE_QUANTITY_SUCCESS = 'DECREASE_QUANTITY_SUCCESS'

export const DELETE_REQ = 'DELETE_REQ'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
